[package]
name = "benches"
resolver = "2"

authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[[bench]]
name = "indicators"
harness = false
path = "indicators.rs"

[[bench]]
name = "prices"
harness = false
path = "prices.rs"

[[bench]]
name = "patterns"
harness = false
path = "patterns.rs"

[dependencies]
core = { path = "../core" }
candlestick = { path = "../patterns/candlestick" }
momentum = { path = "../indicators/momentum" }
price = { path = "../price" }
trend = { path = "../indicators/trend" }
volatility = { path = "../indicators/volatility" }
volume = { path = "../indicators/volume" }
base = { path = "../strategies/base" }

[dev-dependencies]
criterion = { version = "0.5" }