[package]
name = "trail"
resolver = "2"

authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
core = { path = "../../core" }